import { Vujahday_Script } from "next/font/google";
import "./globals.css";

const Viju = Vujahday_Script({ subsets: ["latin"],
weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "React,Next,Javascript, Tailwindcss, CSS, HTML"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Viju.className}>{children}</body>
    </html>
  );
}
